-- ============================================================
-- 坑查查 schema（H2 PostgreSQL 兼容模式，开发期）
-- 生产切 PostgreSQL 时仅需微调类型；向量/全文按 §2.6 演进式接入
-- ============================================================

DROP TABLE IF EXISTS content_tag;
DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS quiz_option;
DROP TABLE IF EXISTS quiz_question;
DROP TABLE IF EXISTS test_record;
DROP TABLE IF EXISTS ugc_story;
DROP TABLE IF EXISTS badge;
DROP TABLE IF EXISTS tool_detection;
DROP TABLE IF EXISTS guardian_alert;
DROP TABLE IF EXISTS guardian_relation;
DROP TABLE IF EXISTS media_asset;

-- 避坑内容（四要素）
CREATE TABLE content (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(128) NOT NULL,
    victim_group  VARCHAR(256),   -- 踩坑人群（要素1）
    trick         VARCHAR(1024),  -- 坑人套路（要素2）
    loss          VARCHAR(512),   -- 损失后果（要素3）
    tip           VARCHAR(512),   -- 避坑常识（要素4）
    slogan        VARCHAR(64),    -- 一句话避坑口诀
    body          VARCHAR(600),   -- 正文（<=200字）
    source_type   INT,            -- 1真实经历 2官方预警 3判例投诉
    source_ref    VARCHAR(256),
    credibility   DOUBLE PRECISION,
    hazard_level  INT,            -- 1低 2中 3高
    loss_amount   INT,            -- 1<1k 2~1w 3~10w 4>10w
    hot_score     INT DEFAULT 0,
    online_at     TIMESTAMP
);

-- 五维标签：dimension 1阶段 2领域 3心理 4渠道 5损失类型
CREATE TABLE content_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id  BIGINT NOT NULL,
    dimension   INT NOT NULL,
    tag         VARCHAR(64) NOT NULL
);
CREATE INDEX idx_ct_content ON content_tag(content_id);
CREATE INDEX idx_ct_dim_tag ON content_tag(dimension, tag);

-- 题库
CREATE TABLE quiz_question (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stem        VARCHAR(512) NOT NULL,
    dimension   VARCHAR(32),   -- 心理/法律/消费/金融/职场/网络
    difficulty  DOUBLE PRECISION DEFAULT 0.5
);

CREATE TABLE quiz_option (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id  BIGINT NOT NULL,
    content      VARCHAR(256) NOT NULL,
    is_correct   BOOLEAN DEFAULT FALSE,
    analysis     VARCHAR(512),
    sort         INT DEFAULT 0
);
CREATE INDEX idx_qo_q ON quiz_option(question_id);

-- 测试记录（JSON 文本列存多维得分/画像/建议）
CREATE TABLE test_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale         INT,
    mode          INT,
    score         INT,
    dim_scores    TEXT,
    profile_tags  TEXT,
    risk_scenes   TEXT,
    advice        TEXT,
    created_at    TIMESTAMP
);

-- 踩坑上报（UGC）
CREATE TABLE ugc_story (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname      VARCHAR(64),
    happen_time   VARCHAR(32),
    region        VARCHAR(64),
    group_tag     VARCHAR(64),
    domain_tag    VARCHAR(64),
    content       VARCHAR(2000) NOT NULL,
    advice        VARCHAR(512),
    like_learn    INT DEFAULT 0,
    like_pity     INT DEFAULT 0,
    audit_status  INT DEFAULT 1,   -- 0待审 1AI通过 2人工通过 3驳回
    created_at    TIMESTAMP
);
CREATE INDEX idx_ugc_audit ON ugc_story(audit_status);

-- 身份徽章
CREATE TABLE badge (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    icon        VARCHAR(16),
    level       INT,
    need_score  INT,
    rarity      INT
);

-- 风险检测记录（私密，仅落脱敏预览与结论；技术方案 §5.5）
CREATE TABLE tool_detection (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_type   INT,            -- 1合同体检 2链接验毒 3拍照识坑 4收款核验
    preview     VARCHAR(64),    -- 输入脱敏预览
    risk_level  INT,            -- 1低 2中 3高
    score       INT,            -- 0-100 风险分
    created_at  TIMESTAMP
);
CREATE INDEX idx_td_created ON tool_detection(created_at);

-- 家人守护关系
CREATE TABLE guardian_relation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name  VARCHAR(64),    -- 守护人（我）
    member_name VARCHAR(64) NOT NULL,  -- 被守护家人
    relation    VARCHAR(32),    -- 父母/子女/配偶/祖辈/其他
    phone_mask  VARCHAR(32),    -- 家人手机号掩码
    topics      VARCHAR(256),   -- 订阅风险领域（逗号分隔）
    voice_first BOOLEAN DEFAULT FALSE,  -- 适老化语音优先
    created_at  TIMESTAMP
);

-- 守护预警（站内提醒，生产经 MQ 推送短信/微信/音箱）
CREATE TABLE guardian_alert (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT NOT NULL,
    content_id  BIGINT,
    member_name VARCHAR(64),
    topic       VARCHAR(64),
    level       INT,
    title       VARCHAR(128),
    body        VARCHAR(512),
    read_flag   BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP
);
CREATE INDEX idx_ga_relation ON guardian_alert(relation_id);

-- 内容素材（海报/GIF/信息长图/音频）
CREATE TABLE media_asset (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id  BIGINT,
    media_type  INT,            -- 1海报 2GIF 3信息长图 4音频(TTS)
    title       VARCHAR(128),
    theme       VARCHAR(32),
    created_at  TIMESTAMP
);
